"""
Shared data models used across the entire trading system.
All inter-agent communication uses these dataclasses.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class PoolData:
    """Represents a single liquidity pool's state."""
    pool_address: str
    token0_symbol: str
    token1_symbol: str
    token0_address: str
    token1_address: str
    reserve0: float           # Amount of token0 in pool
    reserve1: float           # Amount of token1 in pool
    price_token0_in_token1: float  # How much token1 per token0
    price_token1_in_token0: float  # How much token0 per token1
    liquidity_usd: float
    volume_24h_usd: float = 0.0
    fee_tier: float = 0.0025  # 0.25% default PancakeSwap V2 fee
    source: str = "subgraph"
    pool_type: str = "v2"     # "v2" or "v3"
    # V3-specific fields
    tick: int = 0
    fee_24h_usd: float = 0.0


@dataclass
class ArbitrageOpportunity:
    """A detected cross-pool arbitrage opportunity."""
    pool_a: PoolData
    pool_b: PoolData
    token_pair: str            # e.g. "WBNB/USDT"
    buy_pool: str              # Pool address to buy from (cheaper)
    sell_pool: str             # Pool address to sell to (more expensive)
    price_diff_pct: float      # Percentage price difference
    buy_price: float           # Price in buy pool
    sell_price: float          # Price in sell pool
    direction: str             # "buy_A_sell_B" or "buy_B_sell_A"


@dataclass
class TradeProposal:
    """A structured trade proposal generated by the strategy layer."""
    opportunity: ArbitrageOpportunity
    token_in: str              # Address of token to sell
    token_out: str             # Address of token to buy
    token_in_symbol: str
    token_out_symbol: str
    amount_in_usd: float       # Size of the trade in USD
    expected_amount_out: float  # Expected output amount
    expected_profit_usd: float  # Net profit after gas + slippage
    gas_cost_usd: float
    slippage_cost_usd: float
    confidence: float = 0.0    # 0-1 score
    strategy_type: str = "arbitrage"  # "arbitrage", "trend", "mean_reversion"
    stop_loss_pct: float = 0.02       # Per-trade stop-loss (2% default)
    take_profit_pct: float = 0.05     # Per-trade take-profit (5% default)


@dataclass
class TradeResult:
    """Result of an executed (or simulated) trade."""
    proposal: TradeProposal
    success: bool
    tx_hash: str = ""
    actual_amount_out: float = 0.0
    actual_profit_usd: float = 0.0
    gas_used: int = 0
    gas_cost_usd: float = 0.0
    error: str = ""
    timestamp: str = ""
    dry_run: bool = True


@dataclass
class PortfolioState:
    """Current state of the portfolio."""
    capital_usd: float
    total_pnl_usd: float = 0.0
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    consecutive_losses: int = 0
    peak_capital_usd: float = 0.0
    current_drawdown_pct: float = 0.0
    trades: list = field(default_factory=list)

    @property
    def win_rate(self) -> float:
        if self.total_trades == 0:
            return 0.0
        return self.winning_trades / self.total_trades

    @property
    def total_return_pct(self) -> float:
        if self.peak_capital_usd == 0:
            return 0.0
        return (self.capital_usd - self.peak_capital_usd) / self.peak_capital_usd


# ── Market Regime Detection ───────────────────────────────────────

@dataclass
class MarketRegime:
    """Current market regime classification."""
    regime: str = "unknown"  # "trending_up", "trending_down", "mean_reverting", "high_volatility", "low_volatility"
    volatility: float = 0.0        # Rolling price volatility
    volatility_percentile: float = 0.0  # 0-1, relative to history
    trend_strength: float = 0.0    # -1 (strong down) to +1 (strong up)
    mean_reversion_score: float = 0.0  # 0-1, how mean-reverting
    confidence: float = 0.0        # 0-1 confidence in classification


@dataclass
class WhaleAlert:
    """Detected large swap or liquidity event."""
    event_type: str       # "large_swap", "liquidity_add", "liquidity_remove", "new_pool"
    token_pair: str
    amount_usd: float
    pool_address: str = ""
    timestamp: str = ""
    impact_score: float = 0.0  # 0-1, how impactful


@dataclass
class PoolRiskTier:
    """Risk classification for a liquidity pool."""
    pool_address: str
    token_pair: str
    risk_tier: str           # "blue_chip", "mid_cap", "degen"
    liquidity_usd: float
    fee_to_liquidity_ratio: float  # fee_24h / liquidity — higher = more attractive
    reserve_imbalance: float       # how imbalanced reserves are (0 = balanced)
    impermanent_loss_1pct: float   # Estimated IL if price moves 1%
    impermanent_loss_5pct: float   # Estimated IL if price moves 5%
    score: float = 0.0             # Overall pool attractiveness score


@dataclass
class AnomalyAlert:
    """Detected market anomaly requiring defensive action."""
    anomaly_type: str     # "flash_crash", "depeg", "oracle_failure", "liquidity_drain", "volume_spike"
    severity: str         # "low", "medium", "high", "critical"
    token_pair: str = ""
    description: str = ""
    recommended_action: str = "pause"  # "pause", "reduce_exposure", "exit_all"


@dataclass
class MarketState:
    """Aggregated market state built by the Market Intelligence Agent."""
    pools: list[PoolData] = field(default_factory=list)
    opportunities: list[ArbitrageOpportunity] = field(default_factory=list)
    gas_price_gwei: float = 5.0
    block_number: int = 0
    timestamp: str = ""
    # New fields
    regime: MarketRegime = field(default_factory=MarketRegime)
    whale_alerts: list[WhaleAlert] = field(default_factory=list)
    anomalies: list[AnomalyAlert] = field(default_factory=list)
    pool_risk_tiers: list[PoolRiskTier] = field(default_factory=list)
