"""
Shared data models used across the entire trading system.
All inter-agent communication uses these dataclasses.
"""

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class PoolData:
    """Represents a single liquidity pool's state."""
    pool_address: str
    token0_symbol: str
    token1_symbol: str
    token0_address: str
    token1_address: str
    reserve0: float           # Amount of token0 in pool
    reserve1: float           # Amount of token1 in pool
    price_token0_in_token1: float  # How much token1 per token0
    price_token1_in_token0: float  # How much token0 per token1
    liquidity_usd: float
    volume_24h_usd: float = 0.0
    fee_tier: float = 0.0025  # 0.25% default PancakeSwap V2 fee
    source: str = "subgraph"


@dataclass
class ArbitrageOpportunity:
    """A detected cross-pool arbitrage opportunity."""
    pool_a: PoolData
    pool_b: PoolData
    token_pair: str            # e.g. "WBNB/USDT"
    buy_pool: str              # Pool address to buy from (cheaper)
    sell_pool: str             # Pool address to sell to (more expensive)
    price_diff_pct: float      # Percentage price difference
    buy_price: float           # Price in buy pool
    sell_price: float          # Price in sell pool
    direction: str             # "buy_A_sell_B" or "buy_B_sell_A"


@dataclass
class TradeProposal:
    """A structured trade proposal generated by the strategy layer."""
    opportunity: ArbitrageOpportunity
    token_in: str              # Address of token to sell
    token_out: str             # Address of token to buy
    token_in_symbol: str
    token_out_symbol: str
    amount_in_usd: float       # Size of the trade in USD
    expected_amount_out: float  # Expected output amount
    expected_profit_usd: float  # Net profit after gas + slippage
    gas_cost_usd: float
    slippage_cost_usd: float
    confidence: float = 0.0    # 0-1 score


@dataclass
class TradeResult:
    """Result of an executed (or simulated) trade."""
    proposal: TradeProposal
    success: bool
    tx_hash: str = ""
    actual_amount_out: float = 0.0
    actual_profit_usd: float = 0.0
    gas_used: int = 0
    gas_cost_usd: float = 0.0
    error: str = ""
    timestamp: str = ""
    dry_run: bool = True


@dataclass
class PortfolioState:
    """Current state of the portfolio."""
    capital_usd: float
    total_pnl_usd: float = 0.0
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    consecutive_losses: int = 0
    peak_capital_usd: float = 0.0
    current_drawdown_pct: float = 0.0
    trades: list = field(default_factory=list)

    @property
    def win_rate(self) -> float:
        if self.total_trades == 0:
            return 0.0
        return self.winning_trades / self.total_trades

    @property
    def total_return_pct(self) -> float:
        if self.peak_capital_usd == 0:
            return 0.0
        return (self.capital_usd - self.peak_capital_usd) / self.peak_capital_usd


@dataclass
class MarketState:
    """Aggregated market state built by the Market Intelligence Agent."""
    pools: list[PoolData] = field(default_factory=list)
    opportunities: list[ArbitrageOpportunity] = field(default_factory=list)
    gas_price_gwei: float = 5.0
    block_number: int = 0
    timestamp: str = ""
